apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-prd-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jgpjuniorj/gitops.git
    targetRevision: main
    path: clusters/aks-prd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}
