apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Apps de infraestrutura/plataforma (ex.: cloudflared)
  sourceRepos:
    - https://github.com/sua-org/gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
