apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-by-env-hlg
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/jgpjuniorj/gitops.git
        revision: main
        directories:
          - path: envs/hlg/*/overlay
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-hlg'
    spec:
      project: '{{ if eq (index .path.segments 2) "cloudflared" }}project-core{{ else }}project-negocio{{ end }}'
      source:
        repoURL: https://github.com/jgpjuniorj/gitops.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 }}'
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
