apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-hlg-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sua-org/gitops.git
    targetRevision: main
    path: clusters/aks-hlg/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
