apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-hlg-appsets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/jgpjuniorj/gitops.git
    targetRevision: main
    path: applicationsets/hlg
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

