apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-core.yaml
  - project-negocio.yaml
  - argocd-config.yaml
  - argocd-rbac.yaml
  - argocd-image-updater
  - appsets.yaml
  - gestao-financeira-prd.yaml
