apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-negocio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Apps de negócio (gestao-financeira-prd)
  sourceRepos:
    - https://github.com/jgpjuniorj/gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
