apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: gestao-financeira-hlg
images:
  - name: ghcr.io/jgpjuniorj/gestao-financeira-hlg
    newTag: ac477292e173940913e48f40bf126275345196eb
    newName: ghcr.io/jgpjuniorj/gestao-financeira-hlg
