apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    v1/ConfigMap:
      ignoreDifferences: |
        jsonPointers:
          - /metadata/annotations
    apps/Deployment:
      ignoreDifferences: |
        jsonPointers:
          - /spec/replicas
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
