apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-sync-options
  namespace: argocd
data:
  hlg.yaml: |
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
  prd.yaml: |
    syncPolicy: {}
  prd-after-stabilize.yaml: |
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
