apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: info
  # Customize git commit identity (optional, but helps auditing)
  git.commit-user: argocd-image-updater
  git.commit-email: argocd-image-updater@users.noreply.github.com
