apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Official upstream base (controller + CRDs + RBAC + default config)
  - github.com/argoproj-labs/argocd-image-updater/config/default?ref=stable

patchesStrategicMerge:
  - configmap-patch.yaml
